#!/usr/bin/env bash
#SBATCH --nodes=20
#SBATCH --ntasks-per-node=44
#SBATCH --partition=cn
#SBATCH --exclusive
#SBATCH --time=00:30:00
#SBATCH --wckey=P120F:PYTHON
#SBATCH --output=job_%j.out.log
#SBATCH --error=job_%j.err.log


srun -n 880 ./EvalPlanExpGlobalMPI PLEXToEvaluate.csv otPythonModel.py
